// lang_afr.dart
//
// List<String> afrList = [
//   "Génesis",
//   "Exodus",
//   "Levítikus",
//   "Númeri",
//   "Deuteronómium",
//   "Josua",
//   "Rigters",
//   "Rut",
//   "1 Samuel",
//   "2 Samuel",
//   "1 Konings",
//   "2 Konings",
//   "1 Kronieke",
//   "2 Kronieke",
//   "Esra",
//   "Nehemia",
//   "Ester",
//   "Job",
//   "Psalms",
//   "Spreuke",
//   "Prediker",
//   "Hooglied",
//   "Jesaja",
//   "Jeremia",
//   "Klaagliedere",
//   "Eségiël",
//   "Daniël",
//   "Hoséa",
//   "Joël",
//   "Amos",
//   "Obadja",
//   "Jona",
//   "Miga",
//   "Nahum",
//   "Hábakuk",
//   "Sefánja",
//   "Haggai",
//   "Sagaría",
//   "Maleági",
//   "Matthéüs",
//   "Markus",
//   "Lukas",
//   "Johannes",
//   "Handelinge",
//   "Romeine",
//   "1 Korinthiërs",
//   "2 Korinthiërs",
//   "Galásiërs",
//   "Efésiërs",
//   "Filippense",
//   "Kolossense",
//   "1 Thessalonicense",
//   "2 Thessalonicense",
//   "1 Timótheüs",
//   "2 Timótheüs",
//   "Titus",
//   "Filémon",
//   "Hebreërs",
//   "Jakobus",
//   "1 Petrus",
//   "2 Petrus",
//   "1 Johannes",
//   "2 Johannes",
//   "3 Johannes",
//   "Judas",
//   "Openbaring"
// ];
