// lang_latin.dart

List<String> latList = [
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numeri",
    "Deuteronomium",
    "Josue",
    "Judices",
    "Ruth",
    "1 Regum",
    "2 Regum",
    "3 Regum",
    "4 Regum",
    "1 Paralipomenon",
    "2 Paralipomenon",
    "1 Esdræ",
    "2 Esdræ",
    "Esther",
    "Job",
    "Psalmi",
    "Proverbia",
    "Ecclesiastes",
    "Canticum Canticorum",
    "Isaiæ",
    "Jeremiæ",
    "Lamentationes",
    "Ezechielis",
    "Danielis",
    "Osee",
    "Joel",
    "Amos",
    "Abdiæ",
    "Jonæ",
    "Michææ",
    "Nahum",
    "Habacuc",
    "Sophoniae",
    "Aggæi",
    "Zachariæ",
    "Malachiæ",
    "Matthæum",
    "Marcum",
    "Lucam",
    "Ioannem",
    "Actus",
    "ad Romanos",
    "1 ad Corinthios",
    "2 ad Corinthios",
    "ad Galatas",
    "ad Ephesios",
    "ad Philippenses",
    "ad Colossenses",
    "1 ad Thessalonicenses",
    "2 ad Thessalonicenses",
    "1 ad Timotheum",
    "2 ad Timotheum",
    "ad Titum",
    "ad Philemonem",
    "ad Hebræos",
    "Iacobi",
    "1 Petri",
    "2 Petri",
    "1 Ioannis",
    "2 Ioannis",
    "3 Ioannis",
    "Iudæ",
    "Apocalypsis"
  ];
